ASS2_WF::usDirections
DirectionType ASS2_WF.usDirections.selectedDirection
Referenced by ASS2_WF.usDirections.BindDG, ASS2_WF.usDirections.dg1_CellContentClick, ASS2_WF.usDirections.toolStripComboBox1_SelectedIndexChanged.
DictType ASS2_WF.usDirections.dict
Referenced by ASS2_WF.usDirections.Bind, ASS2_WF.usDirections.button1_Click, ASS2_WF.usDirections.toolStripComboBox1_SelectedIndexChanged.
System.ComponentModel.IContainer ASS2_WF.usDirections.components
Required designer variable.
Referenced by ASS2_WF.usDirections.Dispose.
System.Windows.Forms.Label ASS2_WF.usDirections.label1
System.Windows.Forms.ToolStrip ASS2_WF.usDirections.toolStrip1
System.Windows.Forms.DataGridView ASS2_WF.usDirections.dg1
Referenced by ASS2_WF.usDirections.btnSave_Click, ASS2_WF.usDirections.dg1_CellContentClick, ASS2_WF.usDirections.InitializeComponent.
System.Windows.Forms.ToolStripButton ASS2_WF.usDirections.btnAdd
System.Windows.Forms.ToolStripButton ASS2_WF.usDirections.btnSave
System.Windows.Forms.ToolStripComboBox ASS2_WF.usDirections.toolStripComboBox1
Referenced by ASS2_WF.usDirections.toolStripComboBox1_SelectedIndexChanged.
System.Windows.Forms.ToolStripButton ASS2_WF.usDirections.addDirection
System.Windows.Forms.Panel ASS2_WF.usDirections.panel1
System.Windows.Forms.Button ASS2_WF.usDirections.button2
System.Windows.Forms.Button ASS2_WF.usDirections.button1
System.Windows.Forms.TextBox ASS2_WF.usDirections.textBox1
Referenced by ASS2_WF.usDirections.button1_Click.
System.Windows.Forms.Label ASS2_WF.usDirections.label2
System.Windows.Forms.DataGridViewTextBoxColumn ASS2_WF.usDirections.colname
System.Windows.Forms.DataGridViewTextBoxColumn ASS2_WF.usDirections.colwsr
System.Windows.Forms.DataGridViewTextBoxColumn ASS2_WF.usDirections.colpnafrom
System.Windows.Forms.DataGridViewTextBoxColumn ASS2_WF.usDirections.colpnato
System.Windows.Forms.DataGridViewButtonColumn ASS2_WF.usDirections.usun
ASS2_WF.usDirections.usDirections()
References ASS2_WF.usDirections.InitializeComponent.
void ASS2_WF.usDirections.usDirections_Load(object sender, EventArgs e)
References ASS2_WF.usDirections.Bind.
void ASS2_WF.usDirections.Bind()
References ASS2_WF.usDirections.dict, ASS2.DictType.Directions.
Referenced by ASS2_WF.usDirections.button1_Click, ASS2_WF.usDirections.usDirections_Load.
void ASS2_WF.usDirections.toolStripComboBox1_Click(object sender, EventArgs e)
void ASS2_WF.usDirections.toolStripComboBox1_SelectedIndexChanged(object sender, EventArgs e)
References ASS2_WF.usDirections.BindDG, ASS2_WF.usDirections.dict, ASS2.DictType.Directions, ASS2_WF.usDirections.selectedDirection, ASS2_WF.usDirections.toolStripComboBox1.
void ASS2_WF.usDirections.BindDG()
References ASS2_WF.usDirections.selectedDirection.
Referenced by ASS2_WF.usDirections.btnAdd_Click, ASS2_WF.usDirections.btnSave_Click, ASS2_WF.usDirections.dg1_CellContentClick, ASS2_WF.usDirections.toolStripComboBox1_SelectedIndexChanged.
void ASS2_WF.usDirections.addDirection_Click(object sender, EventArgs e)
void ASS2_WF.usDirections.button2_Click(object sender, EventArgs e)
void ASS2_WF.usDirections.button1_Click(object sender, EventArgs e)
References ASS2_WF.usDirections.Bind, ASS2_WF.usDirections.dict, ASS2.DictType.Directions, ASS2_WF.usDirections.textBox1.
void ASS2_WF.usDirections.btnAdd_Click(object sender, EventArgs e)
References ASS2_WF.usDirections.BindDG.
void ASS2_WF.usDirections.dg1_CellContentClick(object sender, DataGridViewCellEventArgs e)
References ASS2_WF.usDirections.BindDG, ASS2_WF.usDirections.dg1, ASS2.DirectionType.Items, ASS2_WF.usDirections.selectedDirection.
void ASS2_WF.usDirections.dg1_CellEndEdit(object sender, DataGridViewCellEventArgs e)
void ASS2_WF.usDirections.btnSave_Click(object sender, EventArgs e)
References ASS2_WF.usDirections.BindDG, ASS2_WF.usDirections.dg1.
void ASS2_WF.usDirections.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
References ASS2_WF.usDirections.dg1.
Referenced by ASS2_WF.usDirections.usDirections.
override void ASS2_WF.usDirections.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References ASS2_WF.usDirections.components.