ASS2::ModbusDriver
ModbusIpMaster ASS2.ModbusDriver.master
Referenced by ASS2.ModbusDriver.ConnectClient, ASS2.ModbusDriver.WriteCoils.
EventHandler<ModbusValueEventArgs> ASS2.ModbusDriver.CoilValueChanged
EventHandler ASS2.ModbusDriver.ModbusConnected
Referenced by ASS2.ModbusDriver.Client_ConnectedChanged.
EventHandler ASS2.ModbusDriver.ModbusDisconnected
Referenced by ASS2.ModbusDriver.Client_ConnectedChanged.
Timer ASS2.ModbusDriver.timer
Referenced by ASS2.ModbusDriver.Client_ConnectedChanged, ASS2.ModbusDriver.ConnectionChange.
Timer ASS2.ModbusDriver.ReconnectTimer
Referenced by ASS2.ModbusDriver.ConnectClient, ASS2.ModbusDriver.StartReconnectTimer.
string ASS2.ModbusDriver.clientip
Referenced by ASS2.ModbusDriver.ConnectClient, ASS2.ModbusDriver.ReconnectTimer_Elapsed.
int ASS2.ModbusDriver.clientport
Referenced by ASS2.ModbusDriver.ConnectClient, ASS2.ModbusDriver.ReconnectTimer_Elapsed.
Dictionary<int, bool> ASS2.ModbusDriver.Coils
bool ASS2.ModbusDriver.Connected
Referenced by ASS2_WF.usMaintenance.button1_Click, ASS2_WF.usMaintenance.button2_Click, ASS2_WF.usMaintenance.button3_Click, ASS2_WF.usMaintenance.button4_Click, ASS2_WF.usMaintenance.button5_Click, ASS2_WF.usMaintenance.button6_Click, ASS2.ModbusDriver.Client_ConnectedChanged, ASS2.ModbusDriver.ConnectionChange, ASS2_WF.usWork.Refreshtimer_Tick, ASS2.ModbusDriver.StartReconnectTimer.
SensorStartDetectionType ASS2.ModbusDriver.StartDetectionSensor
Referenced by ASS2.ModbusDriver.ReadDigitalInputsAsync.
SensorStartParcelType ASS2.ModbusDriver.StartParcelSensor
Referenced by ASS2.ModbusDriver.ReadDigitalInputsAsync.
StopSensorType ASS2.ModbusDriver.StopSensor
Referenced by ASS2.ModbusDriver.ReadDigitalInputsAsync.
TactSensorType ASS2.ModbusDriver.TactSensor
Referenced by ASS2.ModbusDriver.ReadDigitalInputsAsync.
ASS2.ModbusDriver.ModbusDriver()
void ASS2.ModbusDriver.ConnectClient(string ip, int port)
References ASS2.ModbusDriver.clientip, ASS2.ModbusDriver.clientport, ASS2.ModbusDriver.ConnectionChange, ASS2.ModbusDriver.master, ASS2.ModbusDriver.ReconnectTimer.
Referenced by ASS2.ModbusDriver.ReconnectTimer_Elapsed.
void ASS2.ModbusDriver.WriteCoils(int startingAddress, bool[] values)
References ASS2.ModbusDriver.master.
void ASS2.ModbusDriver.StartReconnectTimer()
References ASS2.ModbusDriver.Connected, ASS2.ModbusDriver.ReconnectTimer, ASS2.ModbusDriver.ReconnectTimer_Elapsed.
Referenced by ASS2.ModbusDriver.Client_ConnectedChanged, ASS2.ModbusDriver.ConnectionChange.
void ASS2.ModbusDriver.ReconnectTimer_Elapsed(object sender, ElapsedEventArgs e)
References ASS2.ModbusDriver.clientip, ASS2.ModbusDriver.clientport, ASS2.ModbusDriver.ConnectClient.
Referenced by ASS2.ModbusDriver.StartReconnectTimer.
void ASS2.ModbusDriver.Timer_Elapsed(object sender, ElapsedEventArgs e)
References ASS2.ModbusDriver.ReadDigitalInputsAsync.
Referenced by ASS2.ModbusDriver.Client_ConnectedChanged, ASS2.ModbusDriver.ConnectionChange.
async void ASS2.ModbusDriver.ReadDigitalInputsAsync()
References ASS2.ModbusDriver.ConnectionChange, ASS2.ModbusDriver.StartDetectionSensor, ASS2.ModbusDriver.StartParcelSensor, ASS2.ModbusDriver.StopSensor, ASS2.ModbusDriver.TactSensor.
Referenced by ASS2.ModbusDriver.Timer_Elapsed.
void ASS2.ModbusDriver.ConnectionChange(bool connected)
References ASS2.ModbusDriver.Connected, ASS2.ModbusDriver.StartReconnectTimer, ASS2.ModbusDriver.timer, ASS2.ModbusDriver.Timer_Elapsed.
Referenced by ASS2.ModbusDriver.ConnectClient, ASS2.ModbusDriver.ReadDigitalInputsAsync.
void ASS2.ModbusDriver.Client_ConnectedChanged(object sender)
References ASS2.ModbusDriver.Connected, ASS2.ModbusDriver.ModbusConnected, ASS2.ModbusDriver.ModbusDisconnected, ASS2.ModbusDriver.StartReconnectTimer, ASS2.ModbusDriver.timer, ASS2.ModbusDriver.Timer_Elapsed.