ASS2WEB::_Default
global::System.Web.UI.DataVisualization.Charting.Chart ASS2WEB._Default.chart1
chart1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
Referenced by ASS2WEB._Default.BindChart1.
global::System.Web.UI.WebControls.DropDownList ASS2WEB._Default.ddlcircle
ddlcircle control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.DataVisualization.Charting.Chart ASS2WEB._Default.chart2
chart2 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
Referenced by ASS2WEB._Default.bindc2.
void ASS2WEB._Default.Page_Load(object sender, EventArgs e)
References ASS2WEB._Default.BindChart1, ASS2WEB._Default.BindCirlces.
void ASS2WEB._Default.ddlcircle_SelectedIndexChanged(object sender, EventArgs e)
References ASS2WEB._Default.bindc2.
void ASS2WEB._Default.BindChart1()
References ASS2WEB._Default.chart1.
Referenced by ASS2WEB._Default.Page_Load.
void ASS2WEB._Default.BindCirlces()
References ASS2WEB._Default.bindc2.
Referenced by ASS2WEB._Default.Page_Load.
void ASS2WEB._Default.bindc2()
References ASS2WEB._Default.chart2.
Referenced by ASS2WEB._Default.BindCirlces, ASS2WEB._Default.ddlcircle_SelectedIndexChanged.