MysqlCore
EventHandler MysqlCore.OnConnection
Referenced by DB_Main.
int MysqlCore.OperationCount
Referenced by Connection.
string MysqlCore.ConnectionStr
Referenced by Connection, ConnectionTest.
Dictionary<DateTime, string> MysqlCore.ErrorHistory
Dictionary<DateTime, string> MysqlCore.EventHistory
string MysqlCore.LastError
Referenced by InsertList, UpdateList.
MySqlConnection MysqlCore.con
Referenced by Connection, FillDatatable, GetObject< T >, GetSingleObject< T >, Insert, InsertList, NewGetObjects< T >, NewGetSingleObject< T >, NewInsertList< T >, NewUpdateList< T >, Update, UpdateList.
MySqlCommand MysqlCore.com
Referenced by ExecuteNonQuery, ExecuteScalar, FillDatatable, GetByte, GetCount, GetObject< T >, GetSingleObject< T >, GetString, Insert, InsertList, NewGetObjects< T >, NewGetSingleObject< T >, Update, UpdateList.
MySqlDataAdapter MysqlCore.adpt
Referenced by FillDatatable, GetObject< T >, GetSingleObject< T >, NewGetObjects< T >, NewGetSingleObject< T >.
readonly Parameters MysqlCore.ConParameters
static MysqlCore MysqlCore.DB_Main()
References MysqlCore, OnConnection.
static void MysqlCore.KillSleepConnections(MysqlCore m, int timeout)
void MysqlCore.CreateTable(object o, string dbname, string idcolumnName, string tablename)
References ExecuteNonQuery.
bool MysqlCore.NewUpdate(object o, string tablename, string idcolumn="id", MySqlConnection cn=null)
References ExecuteNonQuery.
Referenced by NewInsertOrUpdate, NewUpdateList< T >.
void MysqlCore.NewInsertOrUpdate(object o, string tablename, string idcolumn="id")
References NewInsert, NewUpdate.
Referenced by ASS2.DataBaseStorageHelper.SaveAsync.
int MysqlCore.NewInsert(object o, string tablename, string idcolumn="id", MySqlConnection cn=null)
References ExecuteScalar.
Referenced by NewInsertList< T >, NewInsertOrUpdate.
T MysqlCore.NewGetSingleObject< T >(string SQLcommand)
References adpt, com, con, Connection, SetPropvalue.
List<T> MysqlCore.NewGetObjects< T >(string SQLcommand)
References adpt, com, con, Connection, SetPropvalue.
string MysqlCore.ConString()
MysqlCore.MysqlCore(string server, string database, string password, string SecondServer=null, bool UseCompression=true, string CharacterSet="utf8", string user="root", int port=3306, int ConnectionTimeout=200, bool ConvertZeroDate=true)
References ConnectionTest.
Referenced by DB_Main.
bool MysqlCore.ConnectionTest()
''' Test połączenia z bazą danych '''
'''
References ConnectionStr.
Referenced by MysqlCore.
MySqlConnection MysqlCore.Connection()
References con, ConnectionStr, OperationCount.
Referenced by ExecuteNonQuery, ExecuteScalar, FillDatatable, GetByte, GetCount, GetObject< T >, GetSingleObject< T >, GetString, Insert, InsertList, NewGetObjects< T >, NewGetSingleObject< T >, Update, UpdateList.
Dictionary<string, object> MysqlCore.toDict(object ob)
Referenced by Insert, InsertList, InsertOrUpdate, Update, UpdateList.
T MysqlCore.GetSingleObject< T >(string SQLcommand)
References adpt, com, con, Connection.
bool MysqlCore.ExecuteNonQuery(string sqlCommand, MySqlConnection cn=null)
References com, Connection.
Referenced by CreateTable, NewUpdate.
string MysqlCore.ExecuteScalar(string sqlCommand, MySqlConnection cn=null)
References com, Connection.
Referenced by NewInsert.
DataTable MysqlCore.FillDatatable(string sqlCommand)
References adpt, com, con, Connection.
string MysqlCore.GetInsertString(string TableName, string IdColumn, Dictionary< string, object > PropertiesDict)
Referenced by Insert, InsertList.
string MysqlCore.GetInsertStringWithoutID(string TableName, string IdColumn, Dictionary< string, object > PropertiesDict)
Referenced by InsertList.
bool MysqlCore.Insert(string TableName, string IdColumn, object ob)
References com, con, Connection, GetInsertString, toDict.
Referenced by InsertOrUpdate.
void MysqlCore.NewUpdateList< T >(List< T > L)
References con, NewUpdate.
void MysqlCore.NewInsertList< T >(List< T > L)
References con, NewInsert.
bool MysqlCore.InsertList(string TableName, string idColumn, List< object > ListOb, bool BezID=true)
''' Insert Listy Obiektów za pomocą transakcji '''
''' TableName ''' ListOb '''
References com, con, Connection, GetInsertString, GetInsertStringWithoutID, LastError, toDict.
String MysqlCore.InsertOnDuplicateUpdate(string id, string value)
string MysqlCore.GetUpdatetString(string TableName, string idColumnName, Dictionary< string, object > PropertiesDict)
Referenced by Update, UpdateList.
bool MysqlCore.InsertOrUpdate(string TableName, string idColumnName, object ob)
References GetCount, Insert, toDict, Update.
bool MysqlCore.Update(string TableName, string idColumnName, object ob)
References com, con, Connection, GetUpdatetString, toDict.
Referenced by InsertOrUpdate.
bool MysqlCore.UpdateList(string TableName, string idColumnName, List< object > ListOb)
''' Update Listy Obiektów za pomocą transakcji '''
''' TableName ''' ListOb '''
References com, con, Connection, GetUpdatetString, LastError, toDict.
string MysqlCore.GetString(string sqlCommand, string ReturnValueIffNull="")
''' Zwraca String '''
''' sqlCommand '''
References com, Connection.
byte [] MysqlCore.GetByte(string sqlCommand)
''' Zwraca Byte '''
''' sqlCommand '''
References com, Connection.
int MysqlCore.GetCount(string sqlCommand)
''' Zwraca liczbę rekordów Integer '''
''' sqlCommand '''
References com, Connection.
Referenced by InsertOrUpdate.
object MysqlCore.GetObject< T >(string TableName, string idColumnName, string id)
''' Tworzy dowolny obiekt na podstawie dowolnej klasy z pojedynczego rekordu z tabeli '''
''' T ''' TableName ''' idColumnName ''' id '''
References adpt, com, con, Connection.
List<T> MysqlCore.GetObject< T >(string SQLcommand)
''' Tworzy listę obiektów na podstawie dowolnej klasy wg komendy mysQL '''
''' T ''' SQLcommand '''
References adpt, com, con, Connection.
bool MysqlCore.Delete(string TableName, string idColumnName, string id)
bool MysqlCore.Truncate(string TableName)
bool MysqlCore.DropTable(string TableName)
string MysqlCore.InsertUpdateDuplicateKey(string tablename, string columnid, object ob)
References getinsertduplicateString.
void MysqlCore.SetPropvalue(PropertyInfo p, object ob, object c)
Referenced by NewGetObjects< T >, NewGetSingleObject< T >.
string MysqlCore.getinsertduplicateString(object ob)
Referenced by InsertUpdateDuplicateKey.