ASS2WEB::stats
global::System.Web.UI.WebControls.Label ASS2WEB.stats.Label1
Label1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.DropDownList ASS2WEB.stats.ddlrun
ddlrun control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.ImageButton ASS2WEB.stats.imgDownload
imgDownload control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.Label ASS2WEB.stats.Label2
Label2 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.ImageButton ASS2WEB.stats.ImageButton1
ImageButton1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.Label ASS2WEB.stats.Label3
Label3 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.DataVisualization.Charting.Chart ASS2WEB.stats.chart1
chart1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.DataVisualization.Charting.Chart ASS2WEB.stats.chart2
chart2 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.DataVisualization.Charting.Chart ASS2WEB.stats.chart3
chart3 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
void ASS2WEB.stats.Page_Load(object sender, EventArgs e)
References ASS2WEB.stats.BindRuns.
void ASS2WEB.stats.ddlrun_SelectedIndexChanged(object sender, EventArgs e)
References ASS2WEB.stats.BindRunDetails.
void ASS2WEB.stats.ImageButton1_Click(object sender, ImageClickEventArgs e)
void ASS2WEB.stats.imgDownload_Click(object sender, ImageClickEventArgs e)
void ASS2WEB.stats.BindRuns()
Referenced by ASS2WEB.stats.Page_Load.
DataTable ASS2WEB.stats.GetRunData(int runid)
Referenced by ASS2WEB.stats.BindRunDetails.
void ASS2WEB.stats.BindRunDetails(int runid)
References ASS2WEB.stats.GetRunData.
Referenced by ASS2WEB.stats.ddlrun_SelectedIndexChanged.
string ASS2WEB.stats.ToCSV(DataTable dt)