ASS2WEB::sortprograms
global::System.Web.UI.WebControls.Button ASS2WEB.sortprograms.Button1
Button1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.Button ASS2WEB.sortprograms.Button2
Button2 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.GridView ASS2WEB.sortprograms.dg1
dg1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
Referenced by ASS2WEB.sortprograms.SaveDG1.
global::System.Web.UI.WebControls.Label ASS2WEB.sortprograms.lbselsp
lbselsp control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.Button ASS2WEB.sortprograms.Button4
Button4 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.GridView ASS2WEB.sortprograms.dg2
dg2 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
Referenced by ASS2WEB.sortprograms.BindDG2, ASS2WEB.sortprograms.SaveDG2.
void ASS2WEB.sortprograms.Page_Load(object sender, EventArgs e)
References ASS2WEB.sortprograms.BindDG1.
void ASS2WEB.sortprograms.dg1_RowCommand(object sender, GridViewCommandEventArgs e)
References ASS2WEB.sortprograms.BindDG1, ASS2WEB.sortprograms.BindDG2.
void ASS2WEB.sortprograms.dg2_RowDataBound(object sender, GridViewRowEventArgs e)
void ASS2WEB.sortprograms.Button1_Click(object sender, EventArgs e)
References ASS2WEB.sortprograms.AddProgram.
void ASS2WEB.sortprograms.Button2_Click(object sender, EventArgs e)
References ASS2WEB.sortprograms.SaveDG1.
void ASS2WEB.sortprograms.Button4_Click(object sender, EventArgs e)
References ASS2WEB.sortprograms.SaveDG2.
void ASS2WEB.sortprograms.BindDG1()
Referenced by ASS2WEB.sortprograms.AddProgram, ASS2WEB.sortprograms.dg1_RowCommand, ASS2WEB.sortprograms.Page_Load.
void ASS2WEB.sortprograms.BindDG2(int sortprogramid)
References ASS2WEB.sortprograms.dg2.
Referenced by ASS2WEB.sortprograms.dg1_RowCommand, ASS2WEB.sortprograms.SaveDG2.
void ASS2WEB.sortprograms.SaveDG1()
References ASS2WEB.sortprograms.dg1.
Referenced by ASS2WEB.sortprograms.Button2_Click.
void ASS2WEB.sortprograms.SaveDG2()
References ASS2WEB.sortprograms.BindDG2, ASS2WEB.sortprograms.dg2.
Referenced by ASS2WEB.sortprograms.Button4_Click.
void ASS2WEB.sortprograms.AddProgram()
References ASS2WEB.sortprograms.BindDG1.
Referenced by ASS2WEB.sortprograms.Button1_Click.