ASS2WEB::drp
global::System.Web.UI.HtmlControls.HtmlForm ASS2WEB.drp.form1
form1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
void ASS2WEB.drp.Page_Load(object sender, EventArgs e)
References ASS2WEB.drp.dw.
DataTable ASS2WEB.drp.GetRunData(int runid)
Referenced by ASS2WEB.drp.dw.
void ASS2WEB.drp.dw(string runid)
References ASS2WEB.drp.GetRunData, ASS2WEB.drp.ToCSV.
Referenced by ASS2WEB.drp.Page_Load.
string ASS2WEB.drp.ToCSV(DataTable dt)
Referenced by ASS2WEB.drp.dw.