ASS2WEB::ColorsDict
DictType ASS2WEB.ColorsDict.dict
Referenced by ASS2WEB.ColorsDict.Bind, ASS2WEB.ColorsDict.GetDict.
global::System.Web.UI.HtmlControls.HtmlForm ASS2WEB.ColorsDict.form1
form1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.ScriptManager ASS2WEB.ColorsDict.ScriptManager1
ScriptManager1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.Button ASS2WEB.ColorsDict.Button1
Button1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.GridView ASS2WEB.ColorsDict.dg1
dg1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
Referenced by ASS2WEB.ColorsDict.Button1_Click.
void ASS2WEB.ColorsDict.Page_Load(object sender, EventArgs e)
References ASS2WEB.ColorsDict.Bind, ASS2WEB.ColorsDict.GetDict.
void ASS2WEB.ColorsDict.dg1_RowDataBound(object sender, GridViewRowEventArgs e)
void ASS2WEB.ColorsDict.Button1_Click(object sender, EventArgs e)
References ASS2WEB.ColorsDict.Bind, ASS2WEB.ColorsDict.dg1, ASS2WEB.ColorsDict.GetDict.
void ASS2WEB.ColorsDict.GetDict()
References ASS2WEB.ColorsDict.dict.
Referenced by ASS2WEB.ColorsDict.Button1_Click, ASS2WEB.ColorsDict.Page_Load.
void ASS2WEB.ColorsDict.Bind()
References ASS2.DictType.Colors, ASS2WEB.ColorsDict.dict.
Referenced by ASS2WEB.ColorsDict.Button1_Click, ASS2WEB.ColorsDict.Page_Load.