ASS2WEB::dr
global::System.Web.UI.HtmlControls.HtmlForm ASS2WEB.dr.form1
form1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
void ASS2WEB.dr.Page_Load(object sender, EventArgs e)
References ASS2WEB.dr.dw.
DataTable ASS2WEB.dr.GetRunData(int runid)
Referenced by ASS2WEB.dr.dw.
void ASS2WEB.dr.dw(string runid)
References ASS2WEB.dr.GetRunData, ASS2WEB.dr.ToCSV.
Referenced by ASS2WEB.dr.Page_Load.
string ASS2WEB.dr.ToCSV(DataTable dt)
Referenced by ASS2WEB.dr.dw.