ASS2_WF::Form1
MachineType ASS2_WF.Form1.Machine
Referenced by ASS2_WF.Form1.button2_Click, ASS2_WF.Form1.button5_Click, ASS2_WF.Form1.Form1_Load.
System.ComponentModel.IContainer ASS2_WF.Form1.components
Required designer variable.
Referenced by ASS2_WF.Form1.Dispose.
System.Windows.Forms.Panel ASS2_WF.Form1.panel1
System.Windows.Forms.Label ASS2_WF.Form1.label1
System.Windows.Forms.Panel ASS2_WF.Form1.panel2
System.Windows.Forms.Button ASS2_WF.Form1.button1
System.Windows.Forms.Button ASS2_WF.Form1.button2
System.Windows.Forms.Panel ASS2_WF.Form1.pnContainer
Referenced by ASS2_WF.Form1.ClearpnContrainer.
System.Windows.Forms.Button ASS2_WF.Form1.button3
System.Windows.Forms.Button ASS2_WF.Form1.button4
System.Windows.Forms.Button ASS2_WF.Form1.button5
System.Windows.Forms.Panel ASS2_WF.Form1.panel4
System.Windows.Forms.Panel ASS2_WF.Form1.panel3
Referenced by ASS2_WF.Form1.panel4_Resize.
System.Windows.Forms.Button ASS2_WF.Form1.button16
System.Windows.Forms.Button ASS2_WF.Form1.button15
System.Windows.Forms.TextBox ASS2_WF.Form1.txlogin
Referenced by ASS2_WF.Form1.button15_Click.
System.Windows.Forms.Button ASS2_WF.Form1.button12
System.Windows.Forms.Button ASS2_WF.Form1.button13
System.Windows.Forms.Button ASS2_WF.Form1.button14
System.Windows.Forms.Button ASS2_WF.Form1.button9
System.Windows.Forms.Button ASS2_WF.Form1.button10
System.Windows.Forms.Button ASS2_WF.Form1.button11
System.Windows.Forms.Button ASS2_WF.Form1.button8
System.Windows.Forms.Button ASS2_WF.Form1.button7
System.Windows.Forms.Button ASS2_WF.Form1.button6
System.Windows.Forms.Label ASS2_WF.Form1.label3
System.Windows.Forms.Label ASS2_WF.Form1.label2
System.Windows.Forms.Button ASS2_WF.Form1.button17
ASS2_WF.Form1.Form1()
References ASS2_WF.Form1.InitializeComponent.
void ASS2_WF.Form1.Form1_Load(object sender, EventArgs e)
References ASS2_WF.Form1.Machine.
void ASS2_WF.Form1.button3_Click(object sender, EventArgs e)
void ASS2_WF.Form1.button4_Click(object sender, EventArgs e)
void ASS2_WF.Form1.ClearpnContrainer()
References ASS2_WF.Form1.pnContainer.
Referenced by ASS2_WF.Form1.button1_Click, ASS2_WF.Form1.button2_Click, ASS2_WF.Form1.button5_Click.
void ASS2_WF.Form1.button5_Click(object sender, EventArgs e)
References ASS2_WF.Form1.ClearpnContrainer, ASS2.MachineType.CurrentRun, ASS2.RunType.IsWorking, ASS2_WF.Form1.Machine.
void ASS2_WF.Form1.button1_Click(object sender, EventArgs e)
References ASS2_WF.Form1.ClearpnContrainer.
void ASS2_WF.Form1.button2_Click(object sender, EventArgs e)
References ASS2_WF.Form1.ClearpnContrainer, ASS2_WF.Form1.Machine.
void ASS2_WF.Form1.button6_Click(object sender, EventArgs e)
void ASS2_WF.Form1.button7_Click(object sender, EventArgs e)
void ASS2_WF.Form1.button8_Click(object sender, EventArgs e)
void ASS2_WF.Form1.button11_Click(object sender, EventArgs e)
void ASS2_WF.Form1.button10_Click(object sender, EventArgs e)
void ASS2_WF.Form1.button9_Click(object sender, EventArgs e)
void ASS2_WF.Form1.button14_Click(object sender, EventArgs e)
void ASS2_WF.Form1.button13_Click(object sender, EventArgs e)
void ASS2_WF.Form1.button12_Click(object sender, EventArgs e)
void ASS2_WF.Form1.button16_Click(object sender, EventArgs e)
void ASS2_WF.Form1.button15_Click(object sender, EventArgs e)
References ASS2_WF.Form1.txlogin.
void ASS2_WF.Form1.panel4_Resize(object sender, EventArgs e)
References ASS2_WF.Form1.panel3.
void ASS2_WF.Form1.button17_Click(object sender, EventArgs e)
void ASS2_WF.Form1.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by ASS2_WF.Form1.Form1.
override void ASS2_WF.Form1.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References ASS2_WF.Form1.components.