ASS2WEB::directions
global::System.Web.UI.UpdatePanel ASS2WEB.directions.up1
up1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.Button ASS2WEB.directions.dg1add
dg1add control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.Button ASS2WEB.directions.dg1save
dg1save control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.GridView ASS2WEB.directions.dg1
dg1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
Referenced by ASS2WEB.directions.Savedg1, ASS2WEB.directions.selecteddirection.
global::System.Web.UI.WebControls.Button ASS2WEB.directions.dg2add
dg2add control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.Button ASS2WEB.directions.dg2save
dg2save control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.GridView ASS2WEB.directions.dg2
dg2 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
Referenced by ASS2WEB.directions.savedg2.
void ASS2WEB.directions.Page_Load(object sender, EventArgs e)
References ASS2WEB.directions.BindDG1.
void ASS2WEB.directions.dg1_RowCommand(object sender, GridViewCommandEventArgs e)
References ASS2WEB.directions.BindDG1, ASS2WEB.directions.Binddg2, ASS2WEB.directions.GetDict, ASS2WEB.directions.Savedg1.
void ASS2WEB.directions.dg2_RowCommand(object sender, GridViewCommandEventArgs e)
References ASS2WEB.directions.Binddg2, ASS2WEB.directions.GetDict, ASS2WEB.directions.savedg2, ASS2WEB.directions.selecteddirection.
void ASS2WEB.directions.dg1add_Click(object sender, EventArgs e)
References ASS2WEB.directions.BindDG1, ASS2WEB.directions.GetDict, ASS2WEB.directions.Savedg1.
void ASS2WEB.directions.dg1save_Click(object sender, EventArgs e)
References ASS2WEB.directions.Savedg1.
void ASS2WEB.directions.dg2add_Click(object sender, EventArgs e)
References ASS2WEB.directions.Binddg2, ASS2WEB.directions.GetDict, ASS2WEB.directions.savedg2, ASS2WEB.directions.selecteddirection.
void ASS2WEB.directions.dg2save_Click(object sender, EventArgs e)
References ASS2WEB.directions.savedg2.
DictType ASS2WEB.directions.GetDict()
Referenced by ASS2WEB.directions.BindDG1, ASS2WEB.directions.dg1_RowCommand, ASS2WEB.directions.dg1add_Click, ASS2WEB.directions.dg2_RowCommand, ASS2WEB.directions.dg2add_Click, ASS2WEB.directions.Savedg1, ASS2WEB.directions.savedg2, ASS2WEB.directions.selecteddirection.
void ASS2WEB.directions.BindDG1()
References ASS2WEB.directions.GetDict.
Referenced by ASS2WEB.directions.dg1_RowCommand, ASS2WEB.directions.dg1add_Click, ASS2WEB.directions.Page_Load, ASS2WEB.directions.Savedg1.
DirectionType ASS2WEB.directions.selecteddirection()
References ASS2WEB.directions.dg1, ASS2WEB.directions.GetDict.
Referenced by ASS2WEB.directions.Binddg2, ASS2WEB.directions.dg2_RowCommand, ASS2WEB.directions.dg2add_Click, ASS2WEB.directions.savedg2.
void ASS2WEB.directions.Binddg2()
References ASS2WEB.directions.selecteddirection.
Referenced by ASS2WEB.directions.dg1_RowCommand, ASS2WEB.directions.dg2_RowCommand, ASS2WEB.directions.dg2add_Click, ASS2WEB.directions.savedg2.
void ASS2WEB.directions.Savedg1()
References ASS2WEB.directions.BindDG1, ASS2WEB.directions.dg1, ASS2WEB.directions.GetDict.
Referenced by ASS2WEB.directions.dg1_RowCommand, ASS2WEB.directions.dg1add_Click, ASS2WEB.directions.dg1save_Click.
void ASS2WEB.directions.savedg2()
References ASS2WEB.directions.Binddg2, ASS2WEB.directions.dg2, ASS2WEB.directions.GetDict, ASS2WEB.directions.selecteddirection.
Referenced by ASS2WEB.directions.dg2_RowCommand, ASS2WEB.directions.dg2add_Click, ASS2WEB.directions.dg2save_Click.