ASS2_WF::usWork
Timer ASS2_WF.usWork.refreshtimer
Referenced by ASS2_WF.usWork.usWork_Load.
Timer ASS2_WF.usWork.StatTimer
Referenced by ASS2_WF.usWork.usWork_Load.
System.ComponentModel.IContainer ASS2_WF.usWork.components
Required designer variable.
Referenced by ASS2_WF.usWork.Dispose.
System.Windows.Forms.PictureBox ASS2_WF.usWork.pictureBox1
Referenced by ASS2_WF.usWork.InitializeComponent.
System.Windows.Forms.Panel ASS2_WF.usWork.panel1
System.Windows.Forms.ComboBox ASS2_WF.usWork.cbSortProgram
Referenced by ASS2_WF.usWork.InitMachine.
System.Windows.Forms.Label ASS2_WF.usWork.label1
System.Windows.Forms.Button ASS2_WF.usWork.btnStartRun
Referenced by ASS2_WF.usWork.Refreshtimer_Tick.
System.Windows.Forms.Panel ASS2_WF.usWork.panel2
System.Windows.Forms.Label ASS2_WF.usWork.lbRun
Referenced by ASS2_WF.usWork.usWork_Load.
System.Windows.Forms.Panel ASS2_WF.usWork.panel3
System.Windows.Forms.PictureBox ASS2_WF.usWork.pictureBox2
Referenced by ASS2_WF.usWork.InitializeComponent, ASS2_WF.usWork.Refreshtimer_Tick.
System.Windows.Forms.CheckBox ASS2_WF.usWork.checkBox1
Referenced by ASS2_WF.usWork.usWork_Load.
System.Windows.Forms.Label ASS2_WF.usWork.lbTactTime
Referenced by ASS2_WF.usWork.usWork_Load.
System.Windows.Forms.Panel ASS2_WF.usWork.panel4
System.Windows.Forms.Panel ASS2_WF.usWork.panel5
System.Windows.Forms.Label ASS2_WF.usWork.lbFeederParcels
Referenced by ASS2_WF.usWork.usWork_Load.
System.Windows.Forms.Button ASS2_WF.usWork.button1
System.Windows.Forms.Label ASS2_WF.usWork.lbparcelsonline
Referenced by ASS2_WF.usWork.usWork_Load.
System.Windows.Forms.Label ASS2_WF.usWork.lbtactnumber
Referenced by ASS2_WF.usWork.usWork_Load.
System.Windows.Forms.Label ASS2_WF.usWork.lbcirclenumber
Referenced by ASS2_WF.usWork.usWork_Load.
System.Windows.Forms.DataVisualization.Charting.Chart ASS2_WF.usWork.chart1
Referenced by ASS2_WF.usWork.InitializeComponent.
System.Windows.Forms.DataVisualization.Charting.Chart ASS2_WF.usWork.chart2
Referenced by ASS2_WF.usWork.InitializeComponent.
System.Windows.Forms.Label ASS2_WF.usWork.lbsp
System.Windows.Forms.Label ASS2_WF.usWork.lbAllsorted
System.Windows.Forms.Label ASS2_WF.usWork.lbAllMissed
System.Windows.Forms.ListBox ASS2_WF.usWork.listBox1
System.Windows.Forms.Label ASS2_WF.usWork.label2
System.Windows.Forms.Label ASS2_WF.usWork.label3
System.Windows.Forms.Button ASS2_WF.usWork.button2
MachineType ASS2_WF.usWork.machine
Referenced by ASS2_WF.usWork.InitMachine, ASS2_WF.usWork.Refreshtimer_Tick.
System.Windows.Forms.Label ASS2_WF.usWork.label4
ASS2_WF.usWork.usWork()
References ASS2_WF.usWork.InitializeComponent.
void ASS2_WF.usWork.usWork_Load(object sender, EventArgs e)
References ASS2_WF.usWork.BindCharts, ASS2_WF.usWork.checkBox1, ASS2_WF.usWork.lbcirclenumber, ASS2_WF.usWork.lbFeederParcels, ASS2_WF.usWork.lbparcelsonline, ASS2_WF.usWork.lbRun, ASS2_WF.usWork.lbtactnumber, ASS2_WF.usWork.lbTactTime, ASS2_WF.usWork.LoadSortPrograms, ASS2_WF.usWork.Machine_OnLogAdded, ASS2_WF.usWork.refreshtimer, ASS2_WF.usWork.Refreshtimer_Tick, ASS2_WF.usWork.StatTimer, ASS2_WF.usWork.StatTimer_TickAsync.
void ASS2_WF.usWork.Machine_OnLogAdded(object sender, MachineType.MachineLogEventArgs e)
Referenced by ASS2_WF.usWork.usWork_Load.
async void ASS2_WF.usWork.StatTimer_TickAsync(object sender, EventArgs e)
References ASS2_WF.usWork.BindCharts.
Referenced by ASS2_WF.usWork.usWork_Load.
async void ASS2_WF.usWork.Refreshtimer_Tick(object sender, EventArgs e)
References ASS2.MachineType.BeltRunning, ASS2_WF.usWork.btnStartRun, ASS2.ModbusDriver.Connected, ASS2.MachineType.CurrentRun, ASS2.MachineType.Driver, ASS2.RunType.IsWorking, ASS2_WF.usWork.machine, ASS2.MachineType.ParcelsOnRun, ASS2_WF.usWork.pictureBox2.
Referenced by ASS2_WF.usWork.usWork_Load.
void ASS2_WF.usWork.LoadSortPrograms()
References ASS2_WF.usWork.InitMachine.
Referenced by ASS2_WF.usWork.usWork_Load.
void ASS2_WF.usWork.InitMachine()
References ASS2_WF.usWork.cbSortProgram, ASS2.MachineType.InitMachine, ASS2_WF.usWork.machine, ASS2_WF.usWork.ComboboxItem.Value.
Referenced by ASS2_WF.usWork.LoadSortPrograms.
void ASS2_WF.usWork.runText()
void ASS2_WF.usWork.btnStartRun_Click(object sender, EventArgs e)
References ASS2_WF.usWork.ComboboxItem.Value.
void ASS2_WF.usWork.pictureBox1_Click(object sender, EventArgs e)
void ASS2_WF.usWork.panel1_Resize(object sender, EventArgs e)
void ASS2_WF.usWork.button1_Click(object sender, EventArgs e)
async Task ASS2_WF.usWork.BindCharts()
Referenced by ASS2_WF.usWork.StatTimer_TickAsync, ASS2_WF.usWork.usWork_Load.
void ASS2_WF.usWork.button2_Click(object sender, EventArgs e)
void ASS2_WF.usWork.chart1_Resize(object sender, EventArgs e)
void ASS2_WF.usWork.usWork_Resize(object sender, EventArgs e)
void ASS2_WF.usWork.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
References ASS2_WF.usWork.chart1, ASS2_WF.usWork.chart2, ASS2_WF.usWork.pictureBox1, ASS2_WF.usWork.pictureBox2.
Referenced by ASS2_WF.usWork.usWork.
override void ASS2_WF.usWork.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References ASS2_WF.usWork.components.