ASS2WEB::stands
global::System.Web.UI.HtmlControls.HtmlForm ASS2WEB.stands.form1
form1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.Button ASS2WEB.stands.dg1save
dg1save control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.GridView ASS2WEB.stands.dg1
dg1 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
Referenced by ASS2WEB.stands.Savedg1, ASS2WEB.stands.selectedStand.
global::System.Web.UI.WebControls.Button ASS2WEB.stands.dg2save
dg2save control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
global::System.Web.UI.WebControls.GridView ASS2WEB.stands.dg2
dg2 control.
Auto-generated field. To modify move field declaration from designer file to code-behind file.
Referenced by ASS2WEB.stands.savedg2.
void ASS2WEB.stands.Page_Load(object sender, EventArgs e)
References ASS2WEB.stands.BindDG1.
void ASS2WEB.stands.dg1_RowCommand(object sender, GridViewCommandEventArgs e)
References ASS2WEB.stands.Binddg2, ASS2WEB.stands.Savedg1.
void ASS2WEB.stands.dg2_RowCommand(object sender, GridViewCommandEventArgs e)
void ASS2WEB.stands.dg1save_Click(object sender, EventArgs e)
References ASS2WEB.stands.Savedg1.
void ASS2WEB.stands.dg2save_Click(object sender, EventArgs e)
References ASS2WEB.stands.savedg2.
void ASS2WEB.stands.dg2_RowDataBound(object sender, GridViewRowEventArgs e)
DictType ASS2WEB.stands.GetDict()
Referenced by ASS2WEB.stands.BindDG1, ASS2WEB.stands.Savedg1, ASS2WEB.stands.savedg2, ASS2WEB.stands.selectedStand.
void ASS2WEB.stands.BindDG1()
References ASS2WEB.stands.GetDict.
Referenced by ASS2WEB.stands.Page_Load, ASS2WEB.stands.Savedg1.
StandType ASS2WEB.stands.selectedStand()
References ASS2WEB.stands.dg1, ASS2WEB.stands.GetDict.
Referenced by ASS2WEB.stands.Binddg2, ASS2WEB.stands.savedg2.
void ASS2WEB.stands.Binddg2()
References ASS2WEB.stands.selectedStand.
Referenced by ASS2WEB.stands.dg1_RowCommand, ASS2WEB.stands.savedg2.
void ASS2WEB.stands.Savedg1()
References ASS2WEB.stands.BindDG1, ASS2WEB.stands.dg1, ASS2WEB.stands.GetDict.
Referenced by ASS2WEB.stands.dg1_RowCommand, ASS2WEB.stands.dg1save_Click.
void ASS2WEB.stands.savedg2()
References ASS2WEB.stands.Binddg2, ASS2WEB.stands.dg2, ASS2WEB.stands.GetDict, ASS2WEB.stands.selectedStand.
Referenced by ASS2WEB.stands.dg2save_Click.