ASS2_WF::usMaintenance
MachineType ASS2_WF.usMaintenance.machine
Referenced by ASS2_WF.usMaintenance.button1_Click, ASS2_WF.usMaintenance.button2_Click, ASS2_WF.usMaintenance.button3_Click, ASS2_WF.usMaintenance.button4_Click, ASS2_WF.usMaintenance.button5_Click, ASS2_WF.usMaintenance.button6_Click, ASS2_WF.usMaintenance.Machine_OnTacted1, ASS2_WF.usMaintenance.StartParcelSensor_ValueChanged, ASS2_WF.usMaintenance.usMaintenance_Load.
System.ComponentModel.IContainer ASS2_WF.usMaintenance.components
Required designer variable.
Referenced by ASS2_WF.usMaintenance.Dispose.
System.Windows.Forms.Panel ASS2_WF.usMaintenance.panel1
System.Windows.Forms.Label ASS2_WF.usMaintenance.lbCounter
System.Windows.Forms.Label ASS2_WF.usMaintenance.label2
System.Windows.Forms.Panel ASS2_WF.usMaintenance.panel2
System.Windows.Forms.Button ASS2_WF.usMaintenance.button1
System.Windows.Forms.Button ASS2_WF.usMaintenance.button2
System.Windows.Forms.Button ASS2_WF.usMaintenance.button3
System.Windows.Forms.Button ASS2_WF.usMaintenance.button4
System.Windows.Forms.ComboBox ASS2_WF.usMaintenance.comboBox1
System.Windows.Forms.ComboBox ASS2_WF.usMaintenance.comboBox2
Referenced by ASS2_WF.usMaintenance.button5_Click.
System.Windows.Forms.Button ASS2_WF.usMaintenance.button5
System.Windows.Forms.Button ASS2_WF.usMaintenance.button6
System.Windows.Forms.Panel ASS2_WF.usMaintenance.panel3
System.Windows.Forms.Label ASS2_WF.usMaintenance.lbdetectionsensortact
System.Windows.Forms.Label ASS2_WF.usMaintenance.lbstopsensortact
System.Windows.Forms.Label ASS2_WF.usMaintenance.lbparceltact
System.Windows.Forms.Label ASS2_WF.usMaintenance.label5
System.Windows.Forms.Label ASS2_WF.usMaintenance.label4
System.Windows.Forms.Label ASS2_WF.usMaintenance.label3
System.Windows.Forms.Label ASS2_WF.usMaintenance.label1
System.Windows.Forms.Button ASS2_WF.usMaintenance.button7
System.Windows.Forms.Label ASS2_WF.usMaintenance.label6
System.Windows.Forms.ListBox ASS2_WF.usMaintenance.listBox1
System.Windows.Forms.Button ASS2_WF.usMaintenance.button8
System.Windows.Forms.Label ASS2_WF.usMaintenance.lbdetectp
System.Windows.Forms.Label ASS2_WF.usMaintenance.lbstopp
System.Windows.Forms.Label ASS2_WF.usMaintenance.label7
System.Windows.Forms.Label ASS2_WF.usMaintenance.label8
ASS2_WF.usMaintenance.usMaintenance()
References ASS2_WF.usMaintenance.InitializeComponent.
void ASS2_WF.usMaintenance.usMaintenance_Load(object sender, EventArgs e)
References ASS2.DictType.Colors, ASS2.MachineType.dict, ASS2.DictType.Lamps, ASS2_WF.usMaintenance.machine, ASS2_WF.usMaintenance.Machine_OnLogAdded, ASS2_WF.usMaintenance.Machine_OnStartParcelSensorRead, ASS2_WF.usMaintenance.Machine_OnTacted.
void ASS2_WF.usMaintenance.Machine_OnLogAdded(object sender, MachineType.MachineLogEventArgs e)
Referenced by ASS2_WF.usMaintenance.usMaintenance_Load.
void ASS2_WF.usMaintenance.Machine_OnStartParcelSensorRead(object sender, EventArgs e)
Referenced by ASS2_WF.usMaintenance.usMaintenance_Load.
void ASS2_WF.usMaintenance.Machine_OnTacted(object sender, EventArgs e)
Referenced by ASS2_WF.usMaintenance.usMaintenance_Load.
void ASS2_WF.usMaintenance.button1_Click(object sender, EventArgs e)
References ASS2.ModbusDriver.Connected, ASS2.MachineType.Driver, ASS2_WF.usMaintenance.machine.
void ASS2_WF.usMaintenance.button2_Click(object sender, EventArgs e)
References ASS2.ModbusDriver.Connected, ASS2.MachineType.Driver, ASS2_WF.usMaintenance.machine.
void ASS2_WF.usMaintenance.button3_Click(object sender, EventArgs e)
References ASS2.ModbusDriver.Connected, ASS2.MachineType.Driver, ASS2_WF.usMaintenance.machine.
void ASS2_WF.usMaintenance.button4_Click(object sender, EventArgs e)
References ASS2.ModbusDriver.Connected, ASS2.MachineType.Driver, ASS2_WF.usMaintenance.machine.
void ASS2_WF.usMaintenance.button5_Click(object sender, EventArgs e)
References ASS2_WF.usMaintenance.comboBox2, ASS2.ModbusDriver.Connected, ASS2.MachineType.Driver, ASS2_WF.usMaintenance.machine.
void ASS2_WF.usMaintenance.button6_Click(object sender, EventArgs e)
References ASS2.ModbusDriver.Connected, ASS2.MachineType.Driver, ASS2_WF.usMaintenance.machine.
void ASS2_WF.usMaintenance.button7_Click(object sender, EventArgs e)
References ASS2_WF.usMaintenance.Machine_OnTacted1, ASS2_WF.usMaintenance.StartDetectionSensor_ValueChanged, ASS2_WF.usMaintenance.StartParcelSensor_ValueChanged, ASS2_WF.usMaintenance.StopSensor_ValueChanged.
void ASS2_WF.usMaintenance.StartParcelSensor_ValueChanged(object sender, ModbusDriver.ModbusValueEventArgs e)
References ASS2.MachineType.dict, ASS2.MachineType.Driver, ASS2_WF.usMaintenance.machine, ASS2.DictType.Stands, ASS2.DictType.StopSensorTact.
Referenced by ASS2_WF.usMaintenance.button7_Click.
void ASS2_WF.usMaintenance.StartDetectionSensor_ValueChanged(object sender, ModbusDriver.ModbusValueEventArgs e)
Referenced by ASS2_WF.usMaintenance.button7_Click.
void ASS2_WF.usMaintenance.StopSensor_ValueChanged(object sender, ModbusDriver.ModbusValueEventArgs e)
Referenced by ASS2_WF.usMaintenance.button7_Click.
void ASS2_WF.usMaintenance.Machine_OnTacted1(object sender, EventArgs e)
References ASS2_WF.usMaintenance.machine, ASS2.MachineType.ParcelsOnRun.
Referenced by ASS2_WF.usMaintenance.button7_Click.
void ASS2_WF.usMaintenance.button8_Click(object sender, EventArgs e)
void ASS2_WF.usMaintenance.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by ASS2_WF.usMaintenance.usMaintenance.
override void ASS2_WF.usMaintenance.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References ASS2_WF.usMaintenance.components.