ASS2::MachineType
int ASS2.MachineType.Id
Referenced by ASS2.MachineType.InitMachine.
string ASS2.MachineType.Name
Referenced by ASS2.MachineType.InitMachine, ASS2.MachineType.SetSortProgram.
ModbusDriver ASS2.MachineType.Driver
Referenced by ASS2.MachineType.InitMachine.
RoundStatType ASS2.MachineType.RoundStat
List<MachineStatusLogType> ASS2.MachineType.Logs
Referenced by ASS2.MachineType.TactSensor_BeltStart, ASS2.MachineType.TactSensor_BeltStop.
DictType ASS2.MachineType.dict
Referenced by ASS2.MachineType.AllMissed, ASS2.MachineType.AllSorted, ASS2.MachineType.GetStandStats, ASS2.MachineType.InitMachine, ASS2.MachineType.LampTest, ASS2.MachineType.LampTestSingleOn, ASS2.MachineType.SetSortProgram, ASS2.MachineType.Tacted.
SortProgramType ASS2.MachineType.CurrentSortProgram
Referenced by ASS2.FeederType.Startdetectionsensor_ValueChanged.
RunType ASS2.MachineType.CurrentRun
Referenced by ASS2.FeederType.Startdetectionsensor_ValueChanged, ASS2.MachineType.StartDetectionSensor_ValueChanged.
List<ParcelType> ASS2.MachineType.ParcelsOnRun
Referenced by ASS2.MachineType.InitMachine, ASS2.MachineType.PArcelsAtLineTable, ASS2.MachineType.StartParcelSensor_OnLenghtReaded, ASS2.MachineType.StopSensor_ValueChanged, ASS2.MachineType.TactSensor_ValueChanged.
TactSensorType ASS2.MachineType.TactSensor
Referenced by ASS2.MachineType.Counter_OnNewCirle, ASS2.MachineType.InitMachine.
StopSensorType ASS2.MachineType.StopSensor
Referenced by ASS2.MachineType.InitMachine, ASS2.MachineType.StopSensor_ValueChanged.
SensorStartDetectionType ASS2.MachineType.StartDetectionSensor
Referenced by ASS2.MachineType.InitMachine.
SensorStartParcelType ASS2.MachineType.StartParcelSensor
Referenced by ASS2.MachineType.InitMachine.
FeederType ASS2.MachineType.Feeder1
Referenced by ASS2.MachineType.InitMachine, ASS2.MachineType.StartDetectionSensor_ValueChanged, ASS2.MachineType.StartParcelSensor_ValueChanged.
bool ASS2.MachineType.BeltRunning
DataTable ASS2.MachineType.StatTable
Referenced by ASS2.MachineType.InitMachine, ASS2.MachineType.StatTimer_Elapsed.
Timer ASS2.MachineType.StatTimer
Referenced by ASS2.MachineType.InitMachine.
int ASS2.MachineType.StatParcelscount
Referenced by ASS2.MachineType.StartParcelSensor_ValueChanged, ASS2.MachineType.StatTimer_Elapsed.
int ASS2.MachineType.tactsensorread
Referenced by ASS2.MachineType.TactSensor_ValueChanged.
int ASS2.MachineType.startdetectionsensorread
Referenced by ASS2.MachineType.StartDetectionSensor_ValueChanged.
int ASS2.MachineType.startparcelread
Referenced by ASS2.MachineType.StartParcelSensor_ValueChanged.
int ASS2.MachineType.stopsensorread
Referenced by ASS2.MachineType.StopSensor_ValueChanged.
EventHandler ASS2.MachineType.OnTacted
Referenced by ASS2.MachineType.TactSensor_ValueChanged.
EventHandler ASS2.MachineType.OnStartParcelSensorRead
Referenced by ASS2.MachineType.StartParcelSensor_ValueChanged.
EventHandler<MachineLogEventArgs> ASS2.MachineType.OnLogAdded
Referenced by ASS2.MachineType.Driver_ModbusConnected, ASS2.MachineType.Driver_ModbusDisconnected, ASS2.MachineType.TactSensor_BeltStart, ASS2.MachineType.TactSensor_BeltStop, ASS2.MachineType.TactSensor_TactMissed.
ASS2.MachineType.MachineType()
void ASS2.MachineType.InitMachine(int SortProgramID)
References ASS2.CounterType.CircleNumber, ASS2.TactSensorType.Counter, ASS2.MachineType.Counter_OnNewCirle, ASS2.MachineType.dict, ASS2.MachineType.Driver, ASS2.MachineType.Driver_ModbusConnected, ASS2.MachineType.Driver_ModbusDisconnected, ASS2.MachineType.Feeder1, ASS2.MachineType.Id, ASS2.MachineType.Name, ASS2.MachineType.ParcelsOnRun, ASS2.DictType.SerialConfigs, ASS2.MachineType.SetSortProgram, ASS2.DictType.Stands, ASS2.MachineType.StartDetectionSensor, ASS2.MachineType.StartDetectionSensor_ValueChanged, ASS2.MachineType.StartParcelSensor, ASS2.MachineType.StartParcelSensor_OnLenghtReaded, ASS2.MachineType.StartParcelSensor_ValueChanged, ASS2.MachineType.StatTable, ASS2.MachineType.StatTimer, ASS2.MachineType.StatTimer_Elapsed, ASS2.MachineType.StopSensor, ASS2.MachineType.StopSensor_ValueChanged, ASS2.DictType.TactsCount, ASS2.MachineType.TactSensor, ASS2.MachineType.TactSensor_BeltStart, ASS2.MachineType.TactSensor_BeltStop, ASS2.MachineType.TactSensor_TactMissed, ASS2.MachineType.TactSensor_ValueChanged.
async Task<int> ASS2.MachineType.AllSortedAsync()
References ASS2.MachineType.AllSorted.
async Task<int> ASS2.MachineType.AllMissedAsync()
References ASS2.MachineType.AllMissed.
async Task<DataTable> ASS2.MachineType.GetStandStats()
References ASS2.MachineType.dict, ASS2.DictType.Stands.
async Task<DataTable> ASS2.MachineType.PArcelsAtLineTable()
References ASS2.MachineType.ParcelsOnRun.
void ASS2.MachineType.LampTest()
References ASS2.DictType.Colors, ASS2.MachineType.dict, ASS2.DictType.Stands.
void ASS2.MachineType.LampTestSingleOn()
References ASS2.DictType.Colors, ASS2.MachineType.dict, ASS2.DictType.Stands.
void ASS2.MachineType.LampTestTurnOnAll()
void ASS2.MachineType.LampTestTurnOffAll()
void ASS2.MachineType.StartStopRun(int SortProgramId)
Referenced by ASS2.MachineType.StartDetectionSensor_ValueChanged.
DataTable ASS2.MachineType.PrintSettings()
void ASS2.MachineType.StressSimulation()
void ASS2.MachineType.SetSortProgram(int SortProgramID)
References ASS2.MachineType.dict, ASS2.SortProgramType.Items, ASS2.MachineType.Name, ASS2.DictType.Stands.
Referenced by ASS2.MachineType.InitMachine.
void ASS2.MachineType.StatTimer_Elapsed(object sender, ElapsedEventArgs e)
References ASS2.MachineType.StatParcelscount, ASS2.MachineType.StatTable.
Referenced by ASS2.MachineType.InitMachine.
async Task<int> ASS2.MachineType.AllSorted()
References ASS2.MachineType.dict, ASS2.DictType.Stands.
Referenced by ASS2.MachineType.AllSortedAsync.
async Task<int> ASS2.MachineType.AllMissed()
References ASS2.MachineType.dict, ASS2.DictType.Stands.
Referenced by ASS2.MachineType.AllMissedAsync.
void ASS2.MachineType.Driver_ModbusDisconnected(object sender, EventArgs e)
References ASS2.MachineType.OnLogAdded.
Referenced by ASS2.MachineType.InitMachine.
void ASS2.MachineType.Driver_ModbusConnected(object sender, EventArgs e)
References ASS2.MachineType.OnLogAdded.
Referenced by ASS2.MachineType.InitMachine.
void ASS2.MachineType.Counter_OnNewCirle(object sender, EventArgs e)
References ASS2.CounterType.CircleNumber, ASS2.TactSensorType.Counter, ASS2.MachineType.TactSensor.
Referenced by ASS2.MachineType.InitMachine.
void ASS2.MachineType.StartParcelSensor_OnLenghtReaded(object sender, SensorStartParcelType.StartSensorEventArgs e)
References ASS2.MachineType.ParcelsOnRun.
Referenced by ASS2.MachineType.InitMachine.
void ASS2.MachineType.StartParcelSensor_ValueChanged(object sender, ModbusDriver.ModbusValueEventArgs e)
References ASS2.MachineType.Feeder1, ASS2.MachineType.OnStartParcelSensorRead, ASS2.MachineType.startparcelread, ASS2.MachineType.StatParcelscount, ASS2.SensorStartParcelType.Value.
Referenced by ASS2.MachineType.InitMachine.
void ASS2.MachineType.StartDetectionSensor_ValueChanged(object sender, ModbusDriver.ModbusValueEventArgs e)
References ASS2.MachineType.CurrentRun, ASS2.MachineType.Feeder1, ASS2.RunType.IsWorking, ASS2.MachineType.startdetectionsensorread, ASS2.MachineType.StartStopRun, ASS2.SensorStartDetectionType.Value.
Referenced by ASS2.MachineType.InitMachine.
void ASS2.MachineType.StopSensor_ValueChanged(object sender, ModbusDriver.ModbusValueEventArgs e)
References ASS2.MachineType.ParcelsOnRun, ASS2.MachineType.StopSensor, ASS2.MachineType.stopsensorread, ASS2.StopSensorType.TactNumber, ASS2.StopSensorType.Value.
Referenced by ASS2.MachineType.InitMachine.
void ASS2.MachineType.TactSensor_TactMissed(object sender, EventArgs e)
References ASS2.MachineType.OnLogAdded.
Referenced by ASS2.MachineType.InitMachine.
void ASS2.MachineType.TactSensor_BeltStop(object sender, EventArgs e)
References ASS2.MachineType.Logs, ASS2.MachineType.OnLogAdded.
Referenced by ASS2.MachineType.InitMachine.
void ASS2.MachineType.TactSensor_BeltStart(object sender, EventArgs e)
References ASS2.MachineType.Logs, ASS2.MachineType.OnLogAdded.
Referenced by ASS2.MachineType.InitMachine.
void ASS2.MachineType.TactSensor_ValueChanged(object sender, ModbusDriver.ModbusValueEventArgs e)
References ASS2.MachineType.OnTacted, ASS2.MachineType.ParcelsOnRun, ASS2.MachineType.Tacted, ASS2.MachineType.tactsensorread, ASS2.TactSensorType.Value.
Referenced by ASS2.MachineType.InitMachine.
ColorType ASS2.MachineType.GetColor(ColorType.ColorsList colorname)
Referenced by ASS2.MachineType.Tacted.
async void ASS2.MachineType.Tacted()
References ASS2.MachineType.dict, ASS2.MachineType.GetColor, ASS2.DictType.Stands.
Referenced by ASS2.MachineType.TactSensor_ValueChanged.
void ASS2.MachineType.Feeder_OnParcelStartRun(object sender, FeederType.FeederEventArgs e)
void ASS2.MachineType.Tm_Elapsed(object sender, ElapsedEventArgs e)