RS232DeviceType
SerialPort RS232DeviceType._serialPort
Referenced by Connect.
int RS232DeviceType.delay
Referenced by Connect, DataReceived.
string RS232DeviceType.Name
EventHandler<SkanerEventArgs> RS232DeviceType.OnDataReceived
Referenced by DataReceived.
void RS232DeviceType.Disconnect()
void RS232DeviceType.Connect(string PortName, string name, int speed=9600, int delay=0)
References _serialPort, DataReceived, delay, errorrreceived, pinchanged.
void RS232DeviceType.errorrreceived(object sender, EventArgs e)
Referenced by Connect.
void RS232DeviceType.pinchanged(object sender, EventArgs e)
Referenced by Connect.
void RS232DeviceType.DataReceived(object sender, EventArgs e)
References delay, OnDataReceived.
Referenced by Connect.