ASS2::ParcelType
OdrzutyReason
EventHandler<ParcelEventArgs> ASS2.ParcelType.OnParcelStopRun
Referenced by ASS2.ParcelType.StopRun.
int ASS2.ParcelType.Id
string ASS2.ParcelType.GuidID
DateTime ASS2.ParcelType.CreateTime
string ASS2.ParcelType.Number
int ASS2.ParcelType.Lenght
string ASS2.ParcelType.DestinationUnitPostCode
StandType ASS2.ParcelType.DestinationStand
Referenced by ASS2.ParcelType.AddTact, ASS2.FeederType.Startdetectionsensor_ValueChanged.
StandItemType ASS2.ParcelType.DestinationStandItem
Referenced by ASS2.ParcelType.StopRun.
int ASS2.ParcelType.CurrentTactNumber
Referenced by ASS2.ParcelType.AddTact.
int ASS2.ParcelType.RunId
int ASS2.ParcelType.SortProgramID
string ASS2.ParcelType.UPnad
string ASS2.ParcelType.UPdor
DateTime ASS2.ParcelType.Datanad
string ASS2.ParcelType.parceltypename
string ASS2.ParcelType.ParcelTypeCode
int ASS2.ParcelType.RoundCounts
Referenced by ASS2.ParcelType.AddTact, ASS2.ParcelType.StopRun.
bool ASS2.ParcelType.Recircuit
Referenced by ASS2.ParcelType.AddTact.
bool ASS2.ParcelType.visible
int ASS2.ParcelType.StopRunTactNumber
Referenced by ASS2.ParcelType.AddTact.
Timer ASS2.ParcelType.Lamp2OffTimer
ModbusDriver ASS2.ParcelType.driver
ASS2.ParcelType.ParcelType()
ASS2.ParcelType.ParcelType(ModbusDriver Driver, int stopruntactnumber, List< StandType > Stands, int runid, int sortprogramid)
async void ASS2.ParcelType.AddTact(int alltacts)
References ASS2.ParcelType.CurrentTactNumber, ASS2.ParcelType.DestinationStand, ASS2.StandType.Lamp1, ASS2.ParcelType.Lamp1On, ASS2.StandType.Lamp2, ASS2.ParcelType.Lamp2On, ASS2.ParcelType.Recircuit, ASS2.ParcelType.RoundCounts, ASS2.ParcelType.StopRun, ASS2.ParcelType.StopRunTactNumber, ASS2.LampType.TactOnNumber.
void ASS2.ParcelType.NextRound()
void ASS2.ParcelType.StopRun(ref StandItemType standitem)
References ASS2.ParcelType.DestinationStandItem, ASS2.StandItemType.Direction, ASS2.DirectionType.Name, ASS2.ParcelType.OnParcelStopRun, ASS2.ParcelType.RoundCounts.
Referenced by ASS2.ParcelType.AddTact.
async void ASS2.ParcelType.Lamp1On()
Referenced by ASS2.ParcelType.AddTact.
async void ASS2.ParcelType.Lamp2On()
Referenced by ASS2.ParcelType.AddTact.
new async void ASS2.ParcelType.SaveAsync()
async void ASS2.ParcelType.SetNumber(string number, List< StandType > Stands)
References ASS2.ServiceReference1.Przesylka.danePrzesylki, ASS2.ServiceReference1.DanePrzesylki.dataNadania.
Referenced by ASS2.FeederType.Scanned.
void ASS2.ParcelType.SetOdrzuty(List< StandType > Stands, OdrzutyReason Reason)
void ASS2.ParcelType.SetLenght(int lenght)
void ASS2.ParcelType.Lamp2OffTimer_Elapsed(object sender, ElapsedEventArgs e)